<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Quotes</strong> Module Configuration' => '<strong>Zitate</strong> Module Konfiguration',
    'The panel title for the dashboard widget.' => 'Titel des Widget',
    'Height of the widget' => 'Höhe des Widget',
    'Back to modules' => 'Zurück zu den Modulen',
    'Save' => 'Speichern',
    'Quote 1' => 'Zitat 1',
    'Writer quote 1' => 'Verfasser Zitat 1',
    'Quote 2' => 'Zitat 2',
    'Writer quote 2' => 'Verfasser Zitat 2',
    'Quote 3' => 'Zitat 3',
    'Writer quote 3' => 'Verfasser Zitat 3',
    'Quote 4' => 'Zitat 4',
    'Writer quote 4' => 'Verfasser Zitat 4',
    'Quote 5' => 'Zitat 5',
    'Writer quote 5' => 'Verfasser Zitat 5',
    'Quote 6' => 'Zitat 6',
    'Writer quote 6' => 'Verfasser Zitat 6',
    'Quote 7' => 'Zitat 7',
    'Writer quote 7' => 'Verfasser Zitat 7',
    'Quote 8' => 'Zitat 8',
    'Writer quote 8' => 'Verfasser Zitat 8',
    'Quote 9' => 'Zitat 9',
    'Writer quote 9' => 'Verfasser Zitat 9',
    'Quote 10' => 'Zitat 10',
    'Writer quote 10' => 'Verfasser Zitat 10',
    'Quote 11' => 'Zitat 11',
    'Writer quote 11' => 'Verfasser Zitat 11',
    'Quote 12' => 'Zitat 12',
    'Writer quote 12' => 'Verfasser Zitat 12',
    
];
